# Generated by Django 6.0.4 on 2026-04-26 16:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CITIZEN', 'Citizen'), ('OFFICER', 'Officer'), ('FIELD_WORKER', 'Field Worker')], default='CITIZEN', max_length=20)),
                ('civic_points', models.IntegerField(default=15)),
                ('is_deactivated', models.BooleanField(default=False)),
                ('deletion_requested_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CommunityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pseudonymous', models.BooleanField(default=False)),
                ('issue_photo', models.ImageField(blank=True, null=True, upload_to='issue_photos/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Raw citizen text (Manglish/English/Malayalam)')),
                ('category', models.CharField(choices=[('ROAD', 'Road / Pothole'), ('ELECTRICAL', 'Electrical'), ('WATER', 'Water / Drainage'), ('SANITATION', 'Sanitation'), ('STREETLIGHT', 'Streetlight'), ('TREES', 'Trees / Environment'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('image_hash', models.CharField(blank=True, default='', max_length=64)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('landmark_note', models.TextField(blank=True, default='')),
                ('ward_name', models.CharField(blank=True, default='', max_length=100)),
                ('panchayat_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('VALIDATED', 'Validated'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='NEW', max_length=20)),
                ('priority_score', models.IntegerField(default=0)),
                ('is_public_hazard', models.BooleanField(default=False)),
                ('ai_formal_summary', models.TextField(blank=True, default='')),
                ('ai_departments', models.JSONField(blank=True, default=list)),
                ('ai_sentiment', models.CharField(blank=True, choices=[('Neutral', 'Neutral'), ('Frustrated', 'Frustrated'), ('Furious_Threatening', 'Furious / Threatening')], default='', max_length=30)),
                ('ai_seasonality', models.CharField(blank=True, choices=[('Monsoon_Related', 'Monsoon Related'), ('Summer_Drought', 'Summer Drought'), ('Year_Round', 'Year Round')], default='', max_length=30)),
                ('ai_processed', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('resolution_photo', models.ImageField(blank=True, null=True, upload_to='resolution_photos/')),
                ('worker_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_worker', models.ForeignKey(blank=True, limit_choices_to={'role': 'FIELD_WORKER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='following_issues', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
    ]
